### PR TITLE
pedro

### PR DESCRIPTION
**Pull request by prdj**

### CODE REVIEW

**Comment by Ungoot** [comment]
Well done.

**Comment by Benjamin-DCI** [comment]
Nice job Pedro, the solution for `grid` is spot-on.
Two things to change - 
- Making sure the `alt` attribute in the `img` tag is not blank is really important. It helps people with accessibility issues make sense of the page and should always be filled in. Even if its just one word; for example - ` Golf`
- Also make sure the images are in a folder and reference them from there. It helps keep things organised and easier to understand.

**Comment by prdj** [comment]
Hello Benjamin!

Thanks for the feedback, I just pushed the exercise number 52 again.

Yesterday was a very nice lesson and also it was very exciting to hear a bit about your career experiences.

I have music as my biggest hobby and passion 🙂 and I want to go all in developing VST plugins, synthesizers all this kind of things.

Would be amazing if you could help me with some material to study or guiding me somehow.

Best regards!

Pedro

________________________________
De: Benjamin-DCI <notifications@github.com>
Enviado: martes, 14 de abril de 2020 06:23
Para: fbw-28/52-UIB-layout-grid <52-UIB-layout-grid@noreply.github.com>
Cc: pedrinho <pedrojr_dantas@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [fbw-28/52-UIB-layout-grid] pedro (#7)


Nice job Pedro, the solution for grid is spot-on.
Two things to change -

  *   Making sure the alt attribute in the img tag is not blank is really important. It helps people with accessibility issues make sense of the page and should always be filled in. Even if its just one word; for example - Golf
  *   Also make sure the images are in a folder and reference them from there. It helps keep things organised and easier to understand.

**Comment by Benjamin-DCI** [comment]
Great job, merged!

**Pull request merged**
